<?xml version="1.0" encoding="utf-8" ?>
<!-- 对于ID类型的属性,不能是纯数字 -->
<!DOCTYPE cetsix [
<!ELEMENT cetsix (word)*>
<!ELEMENT word (name , mean , lx)>
<!ATTLIST word id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT mean (#PCDATA)>
<!ELEMENT lx (#PCDATA)>
]>
<cetsix>
    <word id="w1">
        <name>words</name>
        <mean>meaning</mean>
        <lx>
            <![CDATA[lx]]>
        </lx>
    </word>
    <word id="w2">
        <name>a.m.</name>
        <mean>上午&lt;br&gt; abbr. (ante meridiem的缩写)上午,午前&lt;br&gt; ad. 上午,由午夜至中午</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w3">
        <name>abacus</name>
        <mean>n. 算盘</mean>
        <lx>
            <![CDATA[ I can use abacus skillfully./r/n     我会熟练地打算盘。/r/n
 The clerk reckoned the expenditure last week with an abacus./r/n     那位职员用算盘将上周的花销计算出来。/r/n]]>
        </lx>
    </word>
    <word id="w4">
        <name>abandon</name>
        <mean>v. 放弃,遗弃,沉溺</mean>
        <lx>
            <![CDATA[ The cruel man abandoned his wife and child./r/n     那个狠心的男人抛弃了他的妻儿。/r/n
 They had abandoned all hope./r/n     他们已经放弃了一切希望。/r/n]]>
        </lx>
    </word>
    <word id="w5">
        <name>abatement</name>
        <mean>n. 减少,减轻,缓和</mean>
        <lx>
            <![CDATA[ A noise abatement notice is served on the club./r/n     向俱乐部发停止大声喧哗的通知。/r/n]]>
        </lx>
    </word>
    <word id="w6">
        <name>abbreviation</name>
        <mean>n. 缩写</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w7">
        <name>ABC</name>
        <mean>n. 基本要素,字母表&lt;br&gt; abbr. 美国广播公司&lt;br&gt; abbr. 澳大利亚广播公司</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w8">
        <name>abdomen</name>
        <mean>n. 腹部</mean>
        <lx>
            <![CDATA[ The spider has a bulgy abdomen./r/n     蜘蛛长着凸出的腹部。/r/n
 He always feels pain in his abdomen./r/n     他的腹部经常疼痛。/r/n]]>
        </lx>
    </word>
    <word id="w9">
        <name>abend</name>
        <mean>异常结束</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w10">
        <name>able</name>
        <mean>a. 能干的,有能力的</mean>
        <lx>
            <![CDATA[ He is an able man./r/n     他是一个能人。/r/n
 As I had plenty of money I was able to help her./r/n     我钱很宽裕，能帮助她。/r/n]]>
        </lx>
    </word>
    <word id="w11">
        <name>abnormal</name>
        <mean>a. 反常的,不正常的,不规则的</mean>
        <lx>
            <![CDATA[ The weather is abnormal this year./r/n     今年的气候不正常。/r/n
 An abnormal fear of high places./r/n     恐高症对于高处的一种不正常的恐惧/r/n]]>
        </lx>
    </word>
    <word id="w12">
        <name>abolish</name>
        <mean>v. 废止,革除</mean>
        <lx>
            <![CDATA[Abraham Lincoln abolished slavery in the United States.
     
亚伯拉罕·林肯在美国废除了奴隶制/n
 There are many bad customs and laws that ought to be abolished     有许多不良的习俗和法规应予以废]]>
        </lx>
    </word>
    <word id="w13">
        <name>aboriginal</name>
        <mean>a. 原始的,土著的</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w14">
        <name>abort</name>
        <mean>v. 流产,打胎,堕胎</mean>
        <lx>
            <![CDATA[ Some suspicious looking men were loitering abort near the house/r/n     几个形迹可疑的人在屋子附近荡来荡去。/r/n
 An aborted organism./r/n     流产的生物体/r/n]]>
        </lx>
    </word>
    <word id="w15">
        <name>abortion</name>
        <mean>n. 流产,堕胎</mean>
        <lx>
            <![CDATA[ Abortion is illegal in this country./r/n     人工流产在这个国家是不合法的。/r/n
 They are discussing the morality of abortion./r/n     他们正在讨论堕胎的道德性。/r/n]]>
        </lx>
    </word>
    <word id="w16">
        <name>abound</name>
        <mean>v. 富于,充满</mean>
        <lx>
            <![CDATA[Tropical plants abound in the jungle.
丛林中有大量的热带植物。
He abounds in courage.
他很有胆量。]]>
        </lx>
    </word>
    <word id="w17">
        <name>above</name>
        <mean>a. 上面的&lt;br&gt; ad. 在上面&lt;br&gt; n. 上面&lt;br&gt; prep. 在...上面</mean>
        <lx>
            <![CDATA[ The sun rose above the horizon./r/n     太阳升到地平线上。/r/n
 My bedroom is just above./r/n     我的卧室就在上面。/r/n]]>
        </lx>
    </word>
    <word id="w18">
        <name>aboveboard</name>
        <mean>ad. 光明正大地,率直地&lt;br&gt; a. 光明正大的,率直的</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w19">
        <name>abrasion</name>
        <mean>n. 磨减,磨损,磨损之处</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w20">
        <name>abrasive</name>
        <mean>n. 研磨剂&lt;br&gt; a. 磨平的</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w21">
        <name>abridge</name>
        <mean>v. 删节,缩短</mean>
        <lx>
            <![CDATA[ It was abridged from the original work./r/n     这是原书的节录本。/r/n
 This is an abridged edition of war and peace"./r/n     这是“战争与和平”的节略版。/r/n"]]>
        </lx>
    </word>
    <word id="w22">
        <name>abridgement</name>
        <mean>节略,缩写</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w23">
        <name>abroad</name>
        <mean>a. 在国外,海外(一般作表语)&lt;br&gt; ad. 到国外,在国外</mean>
        <lx>
            <![CDATA[ He lived abroad for many years./r/n     他在国外居住了许多年。/r/n
 She is hungry for news of her husband working abroad./r/n     她渴望得到国外工作的丈夫的消息。/r/n]]>
        </lx>
    </word>
    <word id="w24">
        <name>abrupt</name>
        <mean>a. 突然的,唐突的</mean>
        <lx>
            <![CDATA[ That young man has an abrupt manner./r/n     那个年轻人态度很无礼。/r/n
 The meeting came to an abrupt end./r/n     会议突然结束了。/r/n]]>
        </lx>
    </word>
    <word id="w25">
        <name>abruption</name>
        <mean>中断,分离</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w26">
        <name>abscess</name>
        <mean>n. 脓疮,溃疡</mean>
        <lx>
            <![CDATA[ The tip of an abscess, a boil, or a pimple, in which pus forms./r/n     脓头中间有脓液的脓疮、疖或丘疹的顶端/r/n
 I think I have an abscess on my gums. This could be serious./r/n     我想我的牙床上有个脓疮，这可能是严重的。/r/n]]>
        </lx>
    </word>
    <word id="w27">
        <name>absence</name>
        <mean>a. 不在,缺席&lt;br&gt; n. 缺乏,缺少,缺席</mean>
        <lx>
            <![CDATA[ Please look after my house during my absence./r/n     我不在时，请帮我看房子。/r/n
 We must invent an excuse for our absence./r/n     我们必须为缺席编造一个藉口。/r/n]]>
        </lx>
    </word>
    <word id="w28">
        <name>absent</name>
        <mean>a. 缺席的&lt;br&gt; vt. 使缺席</mean>
        <lx>
            <![CDATA[ How many students are absent today?/r/n     今天有多少学生缺席？/r/n
 Why was it that he was absent?/r/n     他为什么缺席呢？/r/n]]>
        </lx>
    </word>
    <word id="w29">
        <name>absentminded</name>
        <mean>a. 心不在焉的,茫然的,恍惚的</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w30">
        <name>absorb</name>
        <mean>v. 吸收,吸引...的注意,使全神贯注</mean>
        <lx>
            <![CDATA[ His business absorbs him./r/n     他的业务使他全神贯注。/r/n
 The clever boy absorbed all the knowledge his teacher could give him./r/n     那个聪明的男孩把他老师所能教他的所有的知识都吸收了。/r/n]]>
        </lx>
    </word>
    <word id="w31">
        <name>absorption</name>
        <mean>n. 吸收</mean>
        <lx>
            <![CDATA[ I really appreciate his complete absorption in his work./r/n     我很欣赏他对工作的极端专注。/r/n
 A medicine or an agent that induces absorption./r/n     吸收剂导致吸收的药品或药剂/r/n]]>
        </lx>
    </word>
    <word id="w32">
        <name>abstract</name>
        <mean>n. 摘要&lt;br&gt; a. 抽象的&lt;br&gt; v. 摘要,抽炼</mean>
        <lx>
            <![CDATA[ He has some abstract notion of wanting to change the world./r/n     他有一种要改造世界的空想。/r/n
 We may talk of beautiful things, but beauty itself is abstract./r/n     我们尽可谈论美的事物，然而美本身却是抽象的。/r/n]]>
        </lx>
    </word>
    <word id="w33">
        <name>absurd</name>
        <mean>a. 荒唐的</mean>
        <lx>
            <![CDATA[ What an absurd suggestion!/r/n     多荒谬的建议啊！/r/n
 It was absurd of you to suggest such a thing./r/n     你居然建议这样的事，太可笑了。/r/n]]>
        </lx>
    </word>
    <word id="w34">
        <name>abundance</name>
        <mean>n. 丰富,充裕</mean>
        <lx>
            <![CDATA[ There was an abundance of corn last year./r/n     去年玉米丰收。/r/n
 The state of being profuse; abundance./r/n     丰富极其丰富的状态；充沛/r/n]]>
        </lx>
    </word>
    <word id="w35">
        <name>abundant</name>
        <mean>a. 丰富的,充裕的</mean>
        <lx>
            <![CDATA[ There is abundant firewood in the forest./r/n     森林里有充裕的薪柴可用。/r/n
 Our abundant resources and stable policy provide foreigners with the advantages they invest here./r/n     我们丰富的资源和稳定的政策为外商投资提供了有利条件。/r/n]]>
        </lx>
    </word>
    <word id="w36">
        <name>academic</name>
        <mean>a. 学院的,理论的,学术性的</mean>
        <lx>
            <![CDATA[ The new academic year is coming./r/n     新学年就要来了。/r/n
 The question is purely academic./r/n     这是一个纯学术性的问题。/r/n]]>
        </lx>
    </word>
    <word id="w37">
        <name>academy</name>
        <mean>n. 学院,学术,学会</mean>
        <lx>
            <![CDATA[ He is a student in an academy of music./r/n     他是一所音乐学院的学生。/r/n
 A member of an art, literary, or scientific academy or society./r/n     学会会员艺术、文学、科学学会或团体的成员/r/n]]>
        </lx>
    </word>
    <word id="w38">
        <name>accelerate</name>
        <mean>v. 加速</mean>
        <lx>
            <![CDATA[ The car accelerated as it overtook me./r/n     那辆汽车一加速就超越了我./r/n
 The leader is losing ground as the rest of the runners accelerate./r/n     领先者在其余赛跑者加速时就逐渐失去了优势。/r/n]]>
        </lx>
    </word>
    <word id="w39">
        <name>acceleration</name>
        <mean>n. 加速,促进,加速度</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w40">
        <name>accelerator</name>
        <mean>n. 加速者,加速器,油门</mean>
        <lx>
            <![CDATA[ I pressed the accelerator until the engine screamed./r/n     我猛踩油门踏板，发动机发出了尖利的声音。/r/n
 The brake (pedal) is between the clutch and the accelerator./r/n     制动器（踏板）在离合器和加速器之间./r/n]]>
        </lx>
    </word>
    <word id="w41">
        <name>accentuate</name>
        <mean>v. 以重音念,强调,重读</mean>
        <lx>
            <![CDATA[ The tight jumper only accentuated his fat stomach./r/n     那件紧身套头毛衣反更突出了他那肥胖的肚子./r/n]]>
        </lx>
    </word>
    <word id="w42">
        <name>accept</name>
        <mean>vt.接受,同意,承担(责任等)</mean>
        <lx>
            <![CDATA[ It is generally accepted that smoking is harmful to our health./r/n     吸烟有害健康，这是大家公认的。/r/n
 The police are not allowed to accept rewards./r/n     警察是不允许接受酬金的。/r/n]]>
        </lx>
    </word>
    <word id="w43">
        <name>acceptable</name>
        <mean>a. 合意的,受欢迎的,可接受的</mean>
        <lx>
            <![CDATA[ The solution to this problem is acceptable./r/n     这个问题的解决方案是可接受的。/r/n
 Do you think the proposal is acceptable?/r/n     你认为这个建议可接受吗？/r/n]]>
        </lx>
    </word>
    <word id="w44">
        <name>acceptance</name>
        <mean>n. 接受,容纳,承诺,验证</mean>
        <lx>
            <![CDATA[ Within two days I received a letter of acceptance from the manager./r/n     不到两天，我就收到了经理写来的录取信。/r/n
 The proposal was met with general acceptance./r/n     这建议得到普遍的赞同。/r/n]]>
        </lx>
    </word>
    <word id="w45">
        <name>access</name>
        <mean>n. 通路,进入,使用之权&lt;br&gt; v. 存取</mean>
        <lx>
            <![CDATA[ Citizens may have free access to the library./r/n     市民可以免费使用这个图书馆。/r/n
 He is a man of easy access./r/n     他是一个很好接近的人。/r/n]]>
        </lx>
    </word>
    <word id="w46">
        <name>accessible</name>
        <mean>a. 可得到的,易接近的,可进入的</mean>
        <lx>
            <![CDATA[ A manager should be accessible to his staff./r/n     一个管理人员应该让职员感到平易近人。/r/n
 This island is accessible only by boat./r/n     这个小岛只能坐小船去。/r/n]]>
        </lx>
    </word>
    <word id="w47">
        <name>accident</name>
        <mean>n. 事故,意外的事</mean>
        <lx>
            <![CDATA[ We got back without accident./r/n     我们平安无事地回来了。/r/n
 She was injured badly in the accident./r/n     她在事故中受重伤。/r/n]]>
        </lx>
    </word>
    <word id="w48">
        <name>accidental</name>
        <mean>a. 意外的,偶然的</mean>
        <lx>
            <![CDATA[ Our meeting was quite accidental./r/n     我们的相遇是很偶然的。/r/n
 A sequence of events that although accidental seems to have been planned or arranged./r/n     巧合，凑巧虽是偶然的，但似乎是经计划或安排的一系列事件/r/n]]>
        </lx>
    </word>
    <word id="w49">
        <name>acclaim</name>
        <mean>n. 喝采,欢呼,赞同&lt;br&gt; v. 欢呼,喝采,称赞</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w50">
        <name>accommodate</name>
        <mean>v. 使适应,调节,和解</mean>
        <lx>
            <![CDATA[ The cottage could accommodate up to five people./r/n     这间小屋最多能容纳5个人。/r/n
 The bank is accommodating its customers more than it used to./r/n     这家银行现在给客户贷款比以前多了。/r/n]]>
        </lx>
    </word>
    <word id="w51">
        <name>accompany</name>
        <mean>v. 陪伴,带有</mean>
        <lx>
            <![CDATA[ The text is accompanied by illustration./r/n     正文附有插图。/r/n
 Lightning usually accompanies thunder./r/n     闪电通常伴有雷声。/r/n]]>
        </lx>
    </word>
    <word id="w52">
        <name>accomplish</name>
        <mean>v. 完成</mean>
        <lx>
            <![CDATA[ The prediction was literally accomplished./r/n     这个预言确实实现了。/r/n
 I have accomplished a great deal in the last few months./r/n     在过去几个月里，我完成了相当多的工作。/r/n]]>
        </lx>
    </word>
    <word id="w53">
        <name>accomplishment</name>
        <mean>n. 成就</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w54">
        <name>accord</name>
        <mean>n. 一致,调和,协议，自愿&lt;br&gt; vi. (与)一致（accord with）&lt;br&gt; vt.使一致，调解；给予，赠予
        </mean>
        <lx>
            <![CDATA[ He was accorded a warm welcome./r/n     他受到热烈的欢迎。/r/n
 He joined the army of his own accord./r/n     他自愿参军。/r/n]]>
        </lx>
    </word>
    <word id="w55">
        <name>accordance</name>
        <mean>n. 符合,一致</mean>
        <lx>
            <![CDATA[ I sold the house in accordance with your orders./r/n     我按照你的指示售出了这所房子。/r/n
 The mayor must make policies in accordance with the bill passed in the Congress./r/n     市长要根据议会的议案来制定政策。/r/n]]>
        </lx>
    </word>
    <word id="w56">
        <name>according</name>
        <mean>ad. 根据,按照</mean>
        <lx>
            <![CDATA[ According to these figures, our company is doing well./r/n     从这些数字来看，我们的公司经营得不错。/r/n
 The books in the library were distributed according to subjects./r/n     图书馆里的藏书按科目分类。/r/n]]>
        </lx>
    </word>
    <word id="w57">
        <name>accordingly</name>
        <mean>ad. 因此,于是,如前所说 照着 相应地</mean>
        <lx>
            <![CDATA[ I have told you the circumstances, so you must act accordingly./r/n     我已将情况告诉你，所以你必须酌情处理。/r/n
 He was asked to leave the city and accordingly he went./r/n     有人叫他离开该城市，所以他就走了。/r/n]]>
        </lx>
    </word>
    <word id="w58">
        <name>account</name>
        <mean>n. 帐目,报告,估计&lt;br&gt; v. 叙述,解释&lt;br&gt; n. 利益,好处</mean>
        <lx>
            <![CDATA[ I have an account with Midland Bank./r/n     我在米德兰银行开有户头。/r/n
 He has been asked to account for his conduct./r/n     他被要求解释他的行为。/r/n]]>
        </lx>
    </word>
    <word id="w59">
        <name>accountant</name>
        <mean>n. 会计</mean>
        <lx>
            <![CDATA[ She was defrauded of her money by a dishonest accountant./r/n     她的钱被一个奸诈的会计骗去了。/r/n
 He was deep in conversation with his accountant./r/n     他与会计深入交谈./r/n]]>
        </lx>
    </word>
    <word id="w60">
        <name>accounting</name>
        <mean>n. 会计</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w61">
        <name>accumulate</name>
        <mean>v. 积聚,堆积</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w62">
        <name>accumulation</name>
        <mean>n. 积聚,累积,积聚物</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w63">
        <name>accumulator</name>
        <mean>累加器</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w64">
        <name>accuracy</name>
        <mean>n. 准确(性),精确度</mean>
        <lx>
            <![CDATA[ It is impossible to say with any accuracy how many are affected./r/n     无论如何也说不准受影响的有多少。/r/n
 I can predict something with great accuracy./r/n     我能很准确地预测某事。/r/n]]>
        </lx>
    </word>
    <word id="w65">
        <name>accurate</name>
        <mean>a. 准确的,精确的</mean>
        <lx>
            <![CDATA[ His report of the event was accurate in every detail./r/n     他对事件的报道，其全部细节都是准确的。/r/n
 Is the station clock accurate?/r/n     火车站的表准吗？/r/n]]>
        </lx>
    </word>
    <word id="w66">
        <name>accurately</name>
        <mean>a. 准确地&lt;br&gt; ad. 精确地,准确地</mean>
        <lx>
            <![CDATA[ He can speak English fluently and accurately./r/n     他能准确流利地说英语。/r/n
 The engineer in particular must be able to communicate his ideas to others rapidly and accurately./r/n     工程技术人员尤其必须能够迅速而准确地将自己的想法传达给别人。/r/n]]>
        </lx>
    </word>
    <word id="w67">
        <name>accusation</name>
        <mean>n. 控告,指控,非难</mean>
        <lx>
            <![CDATA[ The accusation was that he had murdered his wife./r/n     罪名是他谋杀了他的妻子。/r/n
 The prosecutor brought an accusation of theft against him./r/n     检察官指控他偷窃。/r/n]]>
        </lx>
    </word>
    <word id="w68">
        <name>accuse</name>
        <mean>v. 责备,控告</mean>
        <lx>
            <![CDATA[ He was accused of incompetence./r/n     他被指责为不称职。/r/n]]>
        </lx>
    </word>
    <word id="w69">
        <name>accuser</name>
        <mean>n. 原告,控诉者,非难者</mean>
        <lx>
            <![CDATA[ The accuser brought an accusation against the accused./r/n     原告起诉了被告。/r/n
 They confronted the prisoner with his accusers./r/n     他们让犯人与原告对质。/r/n]]>
        </lx>
    </word>
    <word id="w70">
        <name>accustom</name>
        <mean>v. 使...习惯</mean>
        <lx>
            <![CDATA[ You must accustom yourself to getting up early./r/n     你必须使自己习惯于早起。/r/n
 He had to accustom himself to the cold weather./r/n     他不得不使自己习惯于寒冷的天气。/r/n]]>
        </lx>
    </word>
    <word id="w71">
        <name>accustomed</name>
        <mean>a. 习惯了的</mean>
        <lx>
            <![CDATA[ You will soon get accustomed to the climate here./r/n     你会很快习惯这里的气候的。/r/n
 I am accustomed to hard work./r/n     我已经习惯努力工作了。/r/n]]>
        </lx>
    </word>
    <word id="w72">
        <name>ache</name>
        <mean>n. 痛&lt;br&gt; v. 痛,渴望</mean>
        <lx>
            <![CDATA[ I ache all over./r/n     我浑身疼痛。/r/n
 He felt a dull ache in his shoulder./r/n     他感到肩膀隐隐作痛。/r/n]]>
        </lx>
    </word>
    <word id="w73">
        <name>achievement</name>
        <mean>n. 成就,成绩,完成,达到</mean>
        <lx>
            <![CDATA[ Flying across the Atlantic for the first time was a great achievement./r/n     首次飞跃大西洋是一项了不起的业绩。/r/n
 I felt a great sense of achievement when I reached the top of the mountain./r/n     当我到达山顶的时候，我有一种巨大的成就感。/r/n]]>
        </lx>
    </word>
    <word id="w74">
        <name>acid</name>
        <mean>a. 酸的&lt;br&gt; n. 酸</mean>
        <lx>
            <![CDATA[ The acid burnt a hole in the carpet./r/n     酸把地毯烧了个洞。/r/n
 Acids react with bases to form salts./r/n     酸与碱反应生成盐。/r/n]]>
        </lx>
    </word>
    <word id="w75">
        <name>acidity</name>
        <mean>n. 酸性,酸度</mean>
        <lx>
            <![CDATA[ Some freshwater fish such as pike can withstand levels of acidity./r/n     一些诸如梭鱼等淡水鱼可以抵御相当程度的酸性。/r/n
 Abnormal acidity of the blood./r/n     酸血症血液中不正常的酸度/r/n]]>
        </lx>
    </word>
    <word id="w76">
        <name>acknowledge</name>
        <mean>v. 承认,答谢,告知收到,确认,报偿</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w77">
        <name>acoustic</name>
        <mean>a. 美声的，听觉的,音感教育,音响学的</mean>
        <lx>
            <![CDATA[ Opened the show with an acoustic set./r/n     不用电子乐器开始演出/r/n
 An acoustic instrument./r/n     非电传音乐器/r/n]]>
        </lx>
    </word>
    <word id="w78">
        <name>acoustics</name>
        <mean>n. 音响学,音响效果,声学</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w79">
        <name>acquaint</name>
        <mean>v. 使...熟知</mean>
        <lx>
            <![CDATA[ I am acquainted with her./r/n     我认识她./r/n
 Please acquaint him with my arrival./r/n     请通知他我到了。/r/n]]>
        </lx>
    </word>
    <word id="w80">
        <name>acquaintance</name>
        <mean>n. 熟人,相识</mean>
        <lx>
            <![CDATA[ I have a slight acquaintance with Japanese./r/n     我略通日文。/r/n
 He is my acquaintance./r/n     他是我的熟人。/r/n]]>
        </lx>
    </word>
    <word id="w81">
        <name>acquire</name>
        <mean>v. 获得,取得,学到</mean>
        <lx>
            <![CDATA[ The collector has acquired a fine collection of impressionist paintings./r/n     这位收藏家收集到大量印象派绘画。/r/n
 We admired his intellectual providence to acquire vast stores of dry information./r/n     我们钦佩他收集大量原始资料的远见卓识。/r/n]]>
        </lx>
    </word>
    <word id="w82">
        <name>acre</name>
        <mean>n. 英亩</mean>
        <lx>
            <![CDATA[ We own 100 acres of farmland./r/n     我们拥有一百英亩农田。/r/n
 The house has half an acre of lawn./r/n     这座房子有半英亩草坪./r/n]]>
        </lx>
    </word>
    <word id="w83">
        <name>acrobat</name>
        <mean>n. 杂技演员</mean>
        <lx>
            <![CDATA[ The audience held its/their breath as the acrobat walked along the tightrope./r/n     杂技演员在钢丝绳上表演时，观众们屏息观看。/r/n
 One that tumbles, especially an acrobat or a gymnast./r/n     翻筋斗者翻滚者，尤指杂技演员或体操运动员/r/n]]>
        </lx>
    </word>
    <word id="w84">
        <name>acronym</name>
        <mean>n. 缩写字,字头语</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w85">
        <name>across</name>
        <mean>ad. 横过&lt;br&gt; prep. 穿过,横过</mean>
        <lx>
            <![CDATA[ The two lines cut across each other./r/n     两条线相交。/r/n
 Can you swim across the river?/r/n     你能游到河的对岸吗？/r/n]]>
        </lx>
    </word>
    <word id="w86">
        <name>act</name>
        <mean>n. 行为,行动,法案&lt;br&gt; v. 行动,扮演,下判决</mean>
        <lx>
            <![CDATA[ Parliament has passed an Act forbidding the killing of rare animals./r/n     国会通过了一项法令, 禁止捕杀珍稀动物。/r/n
 Think well before you act./r/n     要三思而后行。/r/n]]>
        </lx>
    </word>
    <word id="w87">
        <name>ACTH</name>
        <mean>[缩]肾上腺皮质激素</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w88">
        <name>action</name>
        <mean>n. 行动,情节,表现,战斗</mean>
        <lx>
            <![CDATA[ Actions speak louder than words./r/n     行动胜于空谈。/r/n
 The action lasted three hours./r/n     战斗持续了三个小时。/r/n]]>
        </lx>
    </word>
    <word id="w89">
        <name>activate</name>
        <mean>v. 刺激,使...活动,创设</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w90">
        <name>activated</name>
        <mean>激活的</mean>
        <lx>
            <![CDATA[ The burglar alarm was activated by mistake./r/n     防盗铃误响了./r/n]]>
        </lx>
    </word>
    <word id="w91">
        <name>activation</name>
        <mean>n. 激活</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w92">
        <name>active</name>
        <mean>a. 积极的,主动的</mean>
        <lx>
            <![CDATA[ Vesuvius is an active volcano./r/n     维苏威山是一座活火山。/r/n
 She has an active imagination./r/n     她有灵活的想象力。/r/n]]>
        </lx>
    </word>
    <word id="w93">
        <name>activist</name>
        <mean>n. 活动分子,积极分子</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w94">
        <name>activity</name>
        <mean>n. 活动</mean>
        <lx>
            <![CDATA[ The center provides facilities for a whole range of leisure activities./r/n     这个中心提供各种娱乐活动设施。/r/n
 There has been a lot of activity in the town today./r/n     今天市中心相当热闹。/r/n]]>
        </lx>
    </word>
    <word id="w95">
        <name>actress</name>
        <mean>n. 女演员</mean>
        <lx>
            <![CDATA[ The actress won overnight fame with her first film./r/n     这个女演员的第一部电影使她一举成名。/r/n
 The actress wore a black wig over her blond hair./r/n     女演员的金发上戴着黑色的假发。/r/n]]>
        </lx>
    </word>
    <word id="w96">
        <name>actual</name>
        <mean>a. 实际的,真实的</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w97">
        <name>actually</name>
        <mean>ad. 实际上</mean>
        <lx>
            <![CDATA[ Believe it or not, he actually won!/r/n     信不信由你，他真地胜利了！/r/n
 What did he actually say?/r/n     他实际上说了些什么?/r/n]]>
        </lx>
    </word>
    <word id="w98">
        <name>actuals</name>
        <mean>n. 现货</mean>
        <lx>
            <![CDATA[ The actual labour force numbered20820./r/n     实际劳动力有20820人。/r/n
 He told the newspapermen about the conversation, but would not play them the actual tape of it./r/n     他向新闻记者讲了这次谈话的情况，却不愿把实况录音磁带放给他们听。/r/n]]>
        </lx>
    </word>
    <word id="w99">
        <name>actuator</name>
        <mean>执行器</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w100">
        <name>acupressure</name>
        <mean>n. 针压法</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w101">
        <name>acupuncture</name>
        <mean>n. 针灸,针治&lt;br&gt; v. 施以针灸</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w102">
        <name>acute</name>
        <mean>a. 敏锐的,激烈的,尖锐的</mean>
        <lx>
            <![CDATA[ This area has an acute shortage of water./r/n     这个地方缺水严重。/r/n
 We agreed with his acute analysis of the political situation./r/n     我们都同意他对政治形势的深刻分析。/r/n]]>
        </lx>
    </word>
    <word id="w103">
        <name>AD</name>
        <mean>abbr. (advertisement的缩写)广告&lt;br&gt; n. (缩)广告</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w104">
        <name>adapt</name>
        <mean>v. 使...适应,改编</mean>
        <lx>
            <![CDATA[ This novel has been adapted for radio from the Russian original./r/n     这部小说已由俄文原著改编成无线电广播节目。/r/n
 She adapted herself quickly to the new climate./r/n     她很快就适应了这种新气候。/r/n]]>
        </lx>
    </word>
    <word id="w105">
        <name>adaptability</name>
        <mean>n. 适应性</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w106">
        <name>adaptation</name>
        <mean>n. 改编,适应,改编成的作品</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w107">
        <name>adapter</name>
        <mean>适配器</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w108">
        <name>adaptive</name>
        <mean>a. 适合的,适应的,能适应的</mean>
        <lx>
            <![CDATA[ Created adaptive clothing for children and young adults with special needs./r/n     为有特殊要求的儿童或年轻人创造适应的布匹/r/n]]>
        </lx>
    </word>
    <word id="w109">
        <name>add</name>
        <mean>v. 增加</mean>
        <lx>
            <![CDATA[ He added some wood to increase the fire./r/n     他加了一些木柴，使火旺些。/r/n
 If you add 4 to 5, you get 9./r/n     四加五等于九。/r/n]]>
        </lx>
    </word>
    <word id="w110">
        <name>addend</name>
        <mean>加数</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w111">
        <name>adder</name>
        <mean>n. 欧洲产的小毒蛇,北美产的无毒小蛇,加算器</mean>
        <lx>
            <![CDATA[ An adder attacked my father./r/n     一条小毒蛇攻击了我父亲。/r/n]]>
        </lx>
    </word>
    <word id="w112">
        <name>addict</name>
        <mean>v. 使...耽溺,使...上瘾&lt;br&gt; n. 耽溺者,上瘾者</mean>
        <lx>
            <![CDATA[ He was addicted to cocaine./r/n     他吸可卡因上瘾/r/n
 There are no lengths to which an addict will not go to obtain his drug./r/n     瘾君子为了得到毒品什麽事都做得出来./r/n]]>
        </lx>
    </word>
    <word id="w113">
        <name>addiction</name>
        <mean>n. 耽溺,上瘾</mean>
        <lx>
            <![CDATA[ An addiction, especially to a narcotic drug./r/n     上瘾上瘾，特别是对毒品上瘾/r/n
 His addiction to drugs propelled him towards a life of crime./r/n     他吸毒成瘾使他走上了犯罪的道路。/r/n]]>
        </lx>
    </word>
    <word id="w114">
        <name>addition</name>
        <mean>n. 增加,附加物,加,加法</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w115">
        <name>additional</name>
        <mean>a. 附加的,另外的</mean>
        <lx>
            <![CDATA[ He had to pay some additional charges./r/n     他不得不付些附加费。/r/n
 You should know the additional responsibilities that are incidental to the job./r/n     你该知道做这项工作要承担额外责任。/r/n]]>
        </lx>
    </word>
    <word id="w116">
        <name>additionally</name>
        <mean>ad. 另外(加之,又)</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w117">
        <name>additive</name>
        <mean>n. 附加物(加法)&lt;br&gt; a. 加添的</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w118">
        <name>address</name>
        <mean>n. 住址&lt;br&gt; n. 致词,讲话&lt;br&gt; vt. 发表演说，写地址，（图书、文章等）讨论（某主题）</mean>
        <lx>
            <![CDATA[ He addressed the audience in an eloquent speech./r/n     他向听众发表了雄辩的演说。/r/n
 There is a letter addressed to you./r/n     有封写给你收的信。/r/n]]>
        </lx>
    </word>
    <word id="w119">
        <name>addressable</name>
        <mean>可寻址的</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w120">
        <name>addressee</name>
        <mean>被访地址</mean>
        <lx>
            <![CDATA[]]>
        </lx>
    </word>
    <word id="w121">
        <name>addressing</name>
        <mean>寻址,访问</mean>
        <lx>
            <![CDATA[ A larger computer storage area, usually used for virtual storage addressing./r/n     一大段计算机存储区，常用于虚拟存储器寻址。/r/n